spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ophtabd
    username: root
    password: Scematha2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ammorhicham15@gmail.com
    password: uqhophuzugpyefbd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update # Change to 'validate' or 'none' in production
    show-sql: true # Active l'affichage des requêtes SQL
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect # Dialect MySQL
  flyway:
    enabled: false # Active Flyway pour les migrations
    baseline-on-migrate: true
    locations: classpath:db/migration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: your-256-bit-secret-key-here
  expiration: 86400000 # 24 hours in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    com.ophta: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG # Active les logs SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Active les logs détaillés
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ophta-app.log

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api.*
      rate-limits:
        - bandwidths:
            - capacity: 20
              time: 1
              unit: minutes
